### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by TimoGoetze** [tcsenpai/spacellama#7]
this model model works from within other clients. But in spaceLLame it produces 403. Any Idea?

Error: Error: HTTP error! status: 403, message:
{
  "endpoint": "http://192.168.1.123:11434/api/generate",
  "model": "mistral-nemo:latest",
  "message": "HTTP error! status: 403, message: "
}

System Prompt:
Du bist ein hilfreicher Assistent. Fasse den Text in deutscher Sprache zusammen. 

max token 4000

cheers

**Comment by tcsenpai** [comment]
Hello! If you are using Ollama on Windows, you should set `OLLAMA_ORIGINS` to `*` in your [Windows Environment Variables](https://www.computerhope.com/issues/ch000549.htm).

If you are using MacOS or Linux, you should add `export OLLAMA_ORIGINS="*"` to your `.bashrc` or `.zshrc` file.

Assuming you are on Mac or Linux using zsh:
`cd && echo 'export OLLAMA_ORIGINS="*" ' >> .zshrc`

If you are using Bash:
`cd && echo 'export OLLAMA_ORIGINS="*" ' >> .bashrc`

**Comment by TimoGoetze** [comment]
Thanks, this fixes it for local.
